# Generated by Django 5.1.1 on 2025-01-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_blog_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blog_image",
            field=models.ImageField(blank=True, null=True, upload_to="blogs/"),
        ),
    ]
