# Generated by Django 5.1.1 on 2024-09-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("payment_pending", "Payment pending"),
                    ("completed", "Completed"),
                    ("inprogress", "In progress"),
                ],
                default="payment_pending",
                max_length=20,
            ),
        ),
    ]
