# Generated by Django 5.1.1 on 2024-09-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTPVerification",
        ),
    ]
