# Generated by Django 5.1.1 on 2024-10-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("payment_pending", "Payment pending"),
                    ("completed", "Completed"),
                    ("in_progress", "In progress"),
                    ("rejected", "Rejected"),
                ],
                default="payment_pending",
                max_length=100,
            ),
        ),
    ]
