# Generated by Django 5.1.1 on 2024-11-04 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0015_alter_bakeryaddress_delivery"),
        ("orders", "0008_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="bakery.bakeryaddress",
            ),
        ),
    ]
