# Generated by Django 5.1.1 on 2024-11-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_with_vat",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vat_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
