# Generated by Django 5.1.1 on 2024-11-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_total_with_vat_order_vat_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
