# Generated by Django 5.1.1 on 2024-12-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUNDED", "Refunded"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
