# Generated by Django 5.1.1 on 2024-12-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
