# Generated by Django 5.1.1 on 2024-12-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
