# Generated by Django 5.1.1 on 2024-12-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_alter_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("payment_pending", "Payment pending"),
                    ("delivered", "Delivered"),
                    ("in_progress", "In progress"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                    ("in_transit", "In transit"),
                ],
                default="payment_pending",
                max_length=100,
            ),
        ),
    ]
