# Generated by Django 5.1.1 on 2024-12-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_order_packing_fee_order_platform_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="vat_tax",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
