# Generated by Django 5.1.1 on 2024-12-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_order_vat_tax"),
        ("product", "0058_alter_inventory_bulking_price_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="product.productvariant",
            ),
        ),
    ]
