# Generated by Django 5.1.1 on 2024-12-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_alter_orderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
