# Generated by Django 5.1.1 on 2024-12-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_invoice_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="updated_at",
        ),
    ]
