# Generated by Django 5.1.1 on 2024-12-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_invoice_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
