# Generated by Django 5.1.1 on 2024-12-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0023_alter_invoice_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="draft",
                max_length=50,
                null=True,
                verbose_name="Customer Get Types",
            ),
        ),
    ]
