# Generated by Django 5.1.1 on 2024-12-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_alter_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
