# Generated by Django 5.1.1 on 2024-12-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0025_order_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
    ]
