# Generated by Django 5.1.1 on 2024-12-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0026_remove_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
