# Generated by Django 5.1.1 on 2025-01-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0027_order_coupon_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=50,
                null=True,
                verbose_name="Customer Get Types",
            ),
        ),
    ]
