# Generated by Django 5.1.1 on 2025-01-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_alter_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(auto_created=True, auto_now=True, null=True),
        ),
    ]
