# Generated by Django 5.1.1 on 2025-03-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0030_alter_invoice_updated_at_alter_order_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="packing_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="platform_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
