# Generated by Django 5.1.1 on 2025-03-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0031_alter_order_packing_fee_alter_order_platform_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
