# Generated by Django 5.1.1 on 2024-10-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_task_end_date_alter_task_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("in_progress", "Inprogress"),
                    ("completed", "Completed"),
                    ("not_started", "Notstarted"),
                ],
                default="unassigned",
                max_length=200,
            ),
        ),
    ]
