# Generated by Django 5.1.1 on 2024-11-05 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 11, 5, 9, 58, 4, 289272, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateField(),
        ),
    ]
