# Generated by Django 5.1.1 on 2025-01-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0005_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("assigned", "Assigned"),
                    ("in_progress", "Inprogress"),
                    ("completed", "Completed"),
                    ("not_started", "Notstarted"),
                    ("hold", "Hold"),
                ],
                default="unassigned",
                max_length=200,
            ),
        ),
    ]
