# Generated by Django 5.1.1 on 2025-01-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_alter_invoice_status"),
        ("todos", "0006_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="order_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_owned",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("assigned", "Assigned"),
                    ("in_progress", "Inprogress"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("not_started", "Notstarted"),
                    ("hold", "Hold"),
                ],
                default="unassigned",
                max_length=200,
            ),
        ),
    ]
