# Generated by Django 5.1.1 on 2025-01-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0007_task_order_task_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
