# Generated by Django 5.1.1 on 2025-01-15 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_alter_invoice_status"),
        ("todos", "0008_task_end_time_task_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="order_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_task",
                to="orders.order",
            ),
        ),
    ]
