# Generated by Django 5.1.1 on 2025-02-11 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0029_invoice_due_date"),
        ("todos", "0009_alter_task_order_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="order_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="orders.order",
            ),
        ),
    ]
