# Generated by Django 5.1.1 on 2025-03-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0010_alter_task_order_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
