# Generated by Django 5.1.1 on 2024-09-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="session_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
