# Generated by Django 5.1.1 on 2024-10-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cart_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
