# Generated by Django 5.1.1 on 2024-11-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cart_applied_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_with_vat",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="vat_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
