# Generated by Django 5.1.1 on 2024-12-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_alter_cartitem_cart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FavouriteItem",
        ),
    ]
