# Generated by Django 5.1.1 on 2025-01-10 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_delete_favouriteitem"),
        ("coupon", "0018_coupon_get_applies_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("session_id",), name="unique_session_cart"
            ),
        ),
    ]
