# Generated by Django 5.1.1 on 2025-03-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_cart_unique_session_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
