# Generated by Django 5.1.1 on 2025-03-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_alter_cart_updated_at_alter_cartitem_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="packing_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cart",
            name="platform_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
