# Generated by Django 5.1.1 on 2024-09-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("accountant", "accountant"),
                    ("stock_manager", "stock_manager"),
                    ("worker", "worker"),
                    ("admin", "admin"),
                    ("bakery", "bakery"),
                ],
                default="worker",
                max_length=20,
            ),
        ),
    ]
