# Generated by Django 5.1.1 on 2024-10-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_employeeaddress_state_alter_employeeaddress_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeeaddress",
            old_name="contact_number",
            new_name="contact_no",
        ),
    ]
