# Generated by Django 5.1.1 on 2024-11-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_employeedetail_delete_employeeaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedetail",
            name="shift",
            field=models.CharField(
                choices=[
                    ("DAY", "Day Shift (9 AM - 5 PM)"),
                    ("NIGHT", "Night Shift (11 PM - 7 AM)"),
                    ("SWING", "Swing Shift (3 PM - 11 PM)"),
                ],
                default="DAY",
                max_length=10,
            ),
        ),
    ]
