# Generated by Django 5.1.1 on 2024-11-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_employeedetail_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedetail",
            name="shift",
            field=models.CharField(
                choices=[
                    ("Morning", "Day Shift (9 AM - 5 PM)"),
                    ("Night", "Night Shift (11 PM - 7 AM)"),
                    ("Swing", "Swing Shift (3 PM - 11 PM)"),
                ],
                default="Morning",
                max_length=10,
            ),
        ),
    ]
