# Generated by Django 5.1.1 on 2024-11-18 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_employeedetail_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedetail",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_detail",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
