# Generated by Django 5.1.1 on 2024-11-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_alter_employeedetail_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedetail",
            name="country",
            field=models.CharField(
                choices=[("SE", "SWEDEN")],
                default="SE",
                max_length=100,
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="employeedetail",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Stockholm", "Stockholm"),
                    ("Västernorrland", "Västernorrland"),
                    ("Västmanland", "Västmanland"),
                    ("Västra Götaland", "Västra Götaland"),
                    ("Östergötland", "Östergötland"),
                    ("Dalarna", "Dalarna"),
                    ("Gävleborg", "Gävleborg"),
                    ("Gotland", "Gotland"),
                    ("Halland", "Halland"),
                    ("Jämtland", "Jämtland"),
                    ("Jönköping", "Jönköping"),
                    ("Kalmar", "Kalmar"),
                    ("Kristianstad", "Kristianstad"),
                    ("Kopparberg", "Kopparberg"),
                    ("Skåne", "Skåne"),
                    ("Södermanland", "Södermanland"),
                    ("Uppsala", "Uppsala"),
                    ("Värmland", "Värmland"),
                    ("Västerbotten", "Västerbotten"),
                    ("Blekinge", "Blekinge"),
                    ("Nordmaling", "Nordmaling"),
                    ("Örebro", "Örebro"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
