# Generated by Django 5.1.1 on 2024-12-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_verifyemailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifyemailotp",
            name="email_valid",
            field=models.BooleanField(default=False),
        ),
    ]
