# Generated by Django 5.1.1 on 2024-12-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_verifyemailotp_email_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("accountant", "accountant"),
                    ("stock_manager", "stock_manager"),
                    ("worker", "worker"),
                    ("admin", "admin"),
                    ("bakery", "bakery"),
                    ("customer", "customer"),
                ],
                default="worker",
                max_length=20,
            ),
        ),
    ]
