# Generated by Django 5.1.1 on 2025-01-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedetail",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="employeedetail",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
