# Generated by Django 5.1.1 on 2025-01-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_employeedetail_created_at_employeedetail_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedetail",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("on_leave", "On Leave"),
                    ("terminated", "Terminated"),
                    ("probation", "Probation"),
                    ("resigned", "Resigned"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
