# Generated by Django 5.1.1 on 2025-02-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_employeedetail_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedetail",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FT", "Full-Time"),
                    ("PT", "Part-Time"),
                    ("CT", "Contract"),
                    ("FL", "Freelance"),
                    ("IN", "Internship"),
                    ("TP", "Temporary"),
                    ("RM", "Remote"),
                ],
                default="FT",
                max_length=2,
            ),
        ),
    ]
