# Generated by Django 5.1.1 on 2025-02-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedetail",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employeedetail",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employeedetail",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
