# Generated by Django 5.1.1 on 2025-03-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_alter_employeedetail_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedetail",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
