# Generated by Django 5.1.1 on 2025-03-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_registrationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifyemailotp",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
