# Generated by Django 5.1.1 on 2024-10-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "product",
            "0028_rename_sale_price_date_from_inventory_sale_price_dates_from_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_date", models.DateField(auto_created=True, auto_now_add=True)),
                ("start_date", models.DateField(auto_created=True, auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("code", models.CharField(unique=True)),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("buy_x_get_y", "Buy X Get Y"),
                            ("amount_off_product", "Amount Off Product"),
                            ("amount_off_order", "Amount Off Order"),
                            ("free_shipping", "Free Shipping"),
                        ],
                        default="buy_x_get_y",
                        max_length=100,
                        verbose_name="Coupon Type",
                    ),
                ),
                (
                    "minimum_purchase_requirement",
                    models.CharField(
                        choices=[
                            ("no_requirement", "No Minimum Purchase Requirement"),
                            ("minimum_purchase", "Minimum Purchase Amount"),
                            ("minimum_items", "Minimum Quantity Of Items"),
                        ],
                        default="no_requirement",
                        max_length=100,
                        verbose_name="Minimum Purchase Requirement",
                    ),
                ),
                (
                    "minimum_purchase_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "customer_eligibility",
                    models.CharField(
                        choices=[
                            ("all_customer", "All Customer"),
                            ("specific_customer", "Specific Customer"),
                        ],
                        default="all_customer",
                        max_length=100,
                        verbose_name="Customer Eligibility",
                    ),
                ),
                (
                    "customer_specification",
                    models.CharField(
                        choices=[
                            ("havent_purchased", "Haven't Purchased"),
                            ("recent_purchased", "Recent Purchased"),
                        ],
                        default="havent_purchased",
                        max_length=100,
                        verbose_name="Customer Specification",
                    ),
                ),
                (
                    "maximum_discount_usage",
                    models.CharField(
                        choices=[
                            ("per_customer", "Use Per Customer"),
                            (
                                "limit_discount_usage_time",
                                "Limit Number of Times Discount Usage",
                            ),
                        ],
                        default="per_customer",
                        max_length=100,
                        verbose_name="Maximum Discount Usage",
                    ),
                ),
                ("maximum_usage_value", models.IntegerField(default=0)),
                (
                    "combination",
                    models.CharField(
                        choices=[
                            ("product_discounts", "Product Discounts"),
                            ("order_discounts", "Order Discounts"),
                            ("shipping_discounts", "Shipping Discounts"),
                        ],
                        default="product_discounts",
                        max_length=100,
                        verbose_name="Combination",
                    ),
                ),
                (
                    "shipping_scope",
                    models.CharField(
                        choices=[
                            ("all_states", "All States"),
                            ("specific_states", "Specific States"),
                        ],
                        default="all_states",
                        max_length=50,
                        verbose_name="Shipping Scope",
                    ),
                ),
                (
                    "shipping_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Shipping Rate",
                    ),
                ),
                ("exclude_shipping_rate", models.BooleanField(default=False)),
                (
                    "discount_types",
                    models.CharField(
                        choices=[("percentage", "percentage"), ("ammount", "ammount")],
                        default="percentage",
                        max_length=50,
                        verbose_name="Discount Types",
                    ),
                ),
                ("discount_value", models.IntegerField(default=0)),
                ("start_time", models.TimeField(auto_now=True)),
                ("end_time", models.TimeField(auto_now=True)),
                (
                    "customer_buy_types",
                    models.CharField(
                        choices=[
                            ("minimum_items_quantity", "Minimum Items Quantity"),
                            ("minimum_purchase_amount", "Minimum Purchase Amount"),
                        ],
                        default="minimum_items_quantity",
                        max_length=50,
                        verbose_name="Customer Buy Types",
                    ),
                ),
                ("buy_products_quantity", models.IntegerField(default=0)),
                (
                    "customer_gets_types",
                    models.CharField(
                        choices=[
                            ("minimum_items_quantity", "Minimum Items Quantity"),
                            ("minimum_purchase_amount", "Minimum Purchase Amount"),
                        ],
                        default="minimum_items_quantity",
                        max_length=50,
                        verbose_name="Customer Buy Types",
                    ),
                ),
                ("customer_gets_quantity", models.IntegerField(default=0)),
                (
                    "buy_products",
                    models.ManyToManyField(
                        blank=True, related_name="coupons", to="product.product"
                    ),
                ),
                (
                    "states",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select specific states if shipping scope is 'Specific States'",
                        related_name="coupons",
                        to="coupon.state",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
