# Generated by Django 5.1.1 on 2024-10-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0002_state_abbreviation"),
        (
            "product",
            "0028_rename_sale_price_date_from_inventory_sale_price_dates_from_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="customer_get_products",
            field=models.ManyToManyField(
                blank=True, related_name="customer_get_coupons", to="product.product"
            ),
        ),
    ]
