# Generated by Django 5.1.1 on 2024-10-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0004_coupon_is_active_usercoupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="usage_count",
            field=models.IntegerField(
                default=0, help_text="Current number of times this coupon has been used"
            ),
        ),
    ]
