# Generated by Django 5.1.1 on 2024-10-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0005_coupon_usage_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="combination",
            field=models.CharField(
                blank=True,
                choices=[
                    ("product_discounts", "Product Discounts"),
                    ("order_discounts", "Order Discounts"),
                    ("shipping_discounts", "Shipping Discounts"),
                ],
                default=None,
                max_length=100,
                null=True,
                verbose_name="Combination",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="customer_buy_types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minimum_items_quantity", "Minimum Items Quantity"),
                    ("minimum_purchase_amount", "Minimum Purchase Amount"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Customer Buy Types",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="customer_eligibility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all_customer", "All Customer"),
                    ("specific_customer", "Specific Customer"),
                ],
                default=None,
                max_length=100,
                null=True,
                verbose_name="Customer Eligibility",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="customer_gets_types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minimum_items_quantity", "Minimum Items Quantity"),
                    ("minimum_purchase_amount", "Minimum Purchase Amount"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Customer Buy Types",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="customer_specification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("havent_purchased", "Haven't Purchased"),
                    ("recent_purchased", "Recent Purchased"),
                ],
                default=None,
                max_length=100,
                null=True,
                verbose_name="Customer Specification",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_types",
            field=models.CharField(
                blank=True,
                choices=[("percentage", "percentage"), ("ammount", "ammount")],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Discount Types",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="maximum_discount_usage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("per_customer", "Use Per Customer"),
                    (
                        "limit_discount_usage_time",
                        "Limit Number of Times Discount Usage",
                    ),
                ],
                default=None,
                max_length=100,
                null=True,
                verbose_name="Maximum Discount Usage",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="minimum_purchase_requirement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_requirement", "No Minimum Purchase Requirement"),
                    ("minimum_purchase", "Minimum Purchase Amount"),
                    ("minimum_items", "Minimum Quantity Of Items"),
                ],
                default=None,
                max_length=100,
                null=True,
                verbose_name="Minimum Purchase Requirement",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="shipping_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all_states", "All States"),
                    ("specific_states", "Specific States"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Shipping Scope",
            ),
        ),
    ]
