# Generated by Django 5.1.1 on 2024-11-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0006_alter_coupon_combination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
