# Generated by Django 5.1.1 on 2024-11-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0007_alter_coupon_end_date_alter_coupon_end_time_and_more"),
        ("product", "0031_productvariant_end_series_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="buy_products",
            field=models.ManyToManyField(
                blank=True, related_name="coupons", to="product.productvariant"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="customer_get_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="customer_get_coupons",
                to="product.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="customer_specification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("havent_purchased", "Haven't Purchased"),
                    ("recent_purchased", "Recent Purchased"),
                    ("purchased_once", "Purchased Once"),
                    ("purchased_more_than_once", "Purchased More Than Once"),
                ],
                default=None,
                max_length=100,
                null=True,
                verbose_name="Customer Specification",
            ),
        ),
    ]
