# Generated by Django 5.1.1 on 2024-11-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0008_alter_coupon_buy_products_and_more"),
        ("product", "0037_inventory_end_series_inventory_start_series_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="sepecific_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="specific_products",
                to="product.productvariant",
            ),
        ),
    ]
