# Generated by Django 5.1.1 on 2024-11-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0009_coupon_sepecific_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="applies_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("specific_products", "Specific Products"),
                    ("all_products", "All Products"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Coupon Applies Types",
            ),
        ),
    ]
