# Generated by Django 5.1.1 on 2024-11-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0010_coupon_applies_to"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="sepecific_products",
            new_name="specific_products",
        ),
    ]
