# Generated by Django 5.1.1 on 2024-11-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0011_rename_sepecific_products_coupon_specific_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercoupon",
            name="maximum_usage",
            field=models.IntegerField(default=0),
        ),
    ]
