# Generated by Django 5.1.1 on 2024-11-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0012_usercoupon_maximum_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="discount_types",
            field=models.CharField(
                blank=True,
                choices=[("percentage", "percentage"), ("amount", "amount")],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Discount Types",
            ),
        ),
    ]
