# Generated by Django 5.1.1 on 2024-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0013_alter_coupon_discount_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="customer_gets_discount_value",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="customer_gets_types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("free", "Free"),
                    ("amount_off_each", "Amount Off Each"),
                    ("percentage", "Percentage"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Customer Buy Types",
            ),
        ),
    ]
