# Generated by Django 5.1.1 on 2024-12-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0014_coupon_customer_gets_discount_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="customer_gets_types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("free", "Free"),
                    ("amount_off_each", "Amount Off Each"),
                    ("percentage", "Percentage"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Customer Get Types",
            ),
        ),
    ]
