# Generated by Django 5.1.1 on 2024-12-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0015_alter_coupon_customer_gets_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_deleted",
            field=models.BooleanField(default=True),
        ),
    ]
