# Generated by Django 5.1.1 on 2025-01-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0016_coupon_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="minimum_item_value",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
