# Generated by Django 5.1.1 on 2025-01-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0017_coupon_minimum_item_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="get_applies_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("specific_products", "Specific Products"),
                    ("all_products", "All Products"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Coupon Get Apply Types",
            ),
        ),
    ]
