# Generated by Django 5.1.1 on 2025-01-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0018_coupon_get_applies_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
