# Generated by Django 5.1.1 on 2025-02-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0019_alter_coupon_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="customer_buy_types",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="minimum_purchase_requirement",
        ),
        migrations.AddField(
            model_name="coupon",
            name="minimum_purchase_amount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coupon",
            name="minimum_purchase_item",
            field=models.BooleanField(default=False),
        ),
    ]
