# Generated by Django 5.1.1 on 2025-03-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0020_remove_coupon_customer_buy_types_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
