# Generated by Django 5.1.1 on 2025-03-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0021_alter_coupon_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="minimum_purchase_requirement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_requirement", "No Minimum Purchase Requirement"),
                    ("minimum_purchase", "Minimum Purchase Amount"),
                    ("minimum_items", "Minimum Quantity Of Items"),
                ],
                default=None,
                max_length=100,
                null=True,
                verbose_name="Minimum Purchase Requirement",
            ),
        ),
    ]
