# Generated by Django 5.1.1 on 2024-10-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZipCodeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip_code", models.CharField(max_length=5, unique=True)),
                ("city", models.CharField(max_length=50)),
                ("state_code", models.CharField(max_length=2)),
                ("min_order_quantity", models.PositiveIntegerField()),
                (
                    "delivery_availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("not_available", "Not Available"),
                        ],
                        default="available",
                        max_length=13,
                    ),
                ),
                ("delivery_threshold", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
