# Generated by Django 5.1.1 on 2024-10-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_zipcodeconfig_state_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zipcodeconfig",
            name="delivery_availability",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("not_available", "not_available"),
                ],
                default="available",
                max_length=13,
            ),
        ),
    ]
