# Generated by Django 5.1.1 on 2024-11-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_zipcodeconfig_delivery_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="zipcodeconfig",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
