# Generated by Django 5.1.1 on 2024-11-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_zipcodeconfig_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zipcodeconfig",
            name="delivery_availability",
            field=models.CharField(
                choices=[("available", "Available"), ("unavailable", "Unavailable")],
                default="available",
                max_length=13,
            ),
        ),
    ]
