# Generated by Django 5.1.1 on 2024-11-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_zipcodeconfig_delivery_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zipcodeconfig",
            name="zip_code",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
