# Generated by Django 5.1.1 on 2024-12-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_zipcodeconfig_country_alter_zipcodeconfig_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("reorder_level", models.IntegerField(default=100)),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                ("out_of_stock", models.IntegerField(default=5)),
                (
                    "shipping_charges",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
