# Generated by Django 5.1.1 on 2025-01-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_adminconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminconfiguration",
            name="packing_fee",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="adminconfiguration",
            name="platform_fee",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
