# Generated by Django 5.1.1 on 2025-01-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_adminconfiguration_packing_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminconfiguration",
            name="platform_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=5.0, max_digits=5, null=True
            ),
        ),
    ]
