# Generated by Django 5.1.1 on 2025-01-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_alter_adminconfiguration_platform_fee"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminInvoiceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("company_address", models.TextField(blank=True, null=True)),
                (
                    "company_email",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
