# Generated by Django 5.1.1 on 2025-02-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_admininvoiceconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="zipcodeconfig",
            name="delivery_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="zipcodeconfig",
            name="min_order_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
