# Generated by Django 5.1.1 on 2025-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_zipcodeconfig_delivery_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admininvoiceconfiguration",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
    ]
