# Generated by Django 5.1.1 on 2025-02-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_admininvoiceconfiguration_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zipcodeconfig",
            name="min_order_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
