# Generated by Django 5.1.1 on 2025-02-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_alter_zipcodeconfig_min_order_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminconfiguration",
            name="groq_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminconfiguration",
            name="openai_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminconfiguration",
            name="order_accept_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminconfiguration",
            name="order_restrict_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
