# Generated by Django 5.1.1 on 2025-03-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_adminconfiguration_groq_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminconfiguration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="admininvoiceconfiguration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="zipcodeconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
