# Generated by Django 5.1.1 on 2025-03-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_admininvoiceconfiguration_organization_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admininvoiceconfiguration",
            name="bank_branch",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="admininvoiceconfiguration",
            name="bank_detail",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="admininvoiceconfiguration",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="admininvoiceconfiguration",
            name="iban_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
