# Generated by Django 5.1.1 on 2025-03-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_admininvoiceconfiguration_bank_branch_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admininvoiceconfiguration",
            old_name="bank_detail",
            new_name="account_no",
        ),
    ]
