# Generated by Django 5.1.1 on 2024-11-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("buy_x_get_y", "Message"),
                    ("reminder", "Reminder"),
                    ("alert", "Alert"),
                ],
                default="buy_x_get_y",
                max_length=100,
                verbose_name="Coupon Type",
            ),
        ),
    ]
