# Generated by Django 5.1.1 on 2024-12-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_adminnotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("email", models.CharField(max_length=255)),
                ("subscription", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
