# Generated by Django 5.1.1 on 2025-01-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_emailnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="order_detail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("message", "Message"),
                    ("reminder", "Reminder"),
                    ("alert", "Alert"),
                ],
                default="message",
                max_length=100,
                verbose_name="Coupon Type",
            ),
        ),
    ]
