# Generated by Django 5.1.1 on 2025-01-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_notification_order_detail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="order_detail",
        ),
        migrations.AddField(
            model_name="notification",
            name="meta_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
