# Generated by Django 5.1.1 on 2025-02-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_remove_notification_order_detail_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailnotification",
            old_name="updated_at",
            new_name="update_at",
        ),
    ]
