# Generated by Django 5.1.1 on 2025-02-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0007_rename_updated_at_emailnotification_update_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailnotification",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
