# Generated by Django 5.1.1 on 2024-09-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0002_alter_bakery_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakery",
            name="contact_no_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bakery",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BakeryOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bakery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="bakery.bakery"
                    ),
                ),
            ],
        ),
    ]
