# Generated by Django 5.1.1 on 2024-09-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0003_bakery_contact_no_verified_bakery_email_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bakeryotp",
            name="otp",
        ),
        migrations.AddField(
            model_name="bakeryotp",
            name="email_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="bakeryotp",
            name="phone_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
