# Generated by Django 5.1.1 on 2024-09-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0005_bakeryotp_expires_at_bakeryotp_last_sent_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bakeryotp",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="bakeryotp",
            name="last_sent_at",
        ),
    ]
