# Generated by Django 5.1.1 on 2024-09-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0006_remove_bakeryotp_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakeryotp",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bakeryotp",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
