# Generated by Django 5.1.1 on 2024-09-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0007_bakeryotp_expires_at_bakeryotp_last_sent_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bakeryotp",
            old_name="last_sent_at",
            new_name="last_email_sent_at",
        ),
        migrations.AddField(
            model_name="bakeryotp",
            name="last_sms_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
