# Generated by Django 5.1.1 on 2024-10-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0009_alter_bakery_country_alter_bakery_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakery",
            name="term_condition",
            field=models.BooleanField(default=False),
        ),
    ]
