# Generated by Django 5.1.1 on 2024-10-24 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0010_bakery_term_condition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bakery",
            name="address",
        ),
        migrations.RemoveField(
            model_name="bakery",
            name="city",
        ),
        migrations.RemoveField(
            model_name="bakery",
            name="country",
        ),
        migrations.RemoveField(
            model_name="bakery",
            name="state",
        ),
        migrations.RemoveField(
            model_name="bakery",
            name="zipcode",
        ),
        migrations.CreateModel(
            name="BakeryAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AL", "Alabama"),
                            ("AK", "Alaska"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("DC", "District of Columbia"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("IA", "Iowa"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("ME", "Maine"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("US", "United States")],
                        default="US",
                        max_length=100,
                        verbose_name="Country",
                    ),
                ),
                ("zipcode", models.IntegerField()),
                ("primary", models.BooleanField(default=True)),
                (
                    "bakery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bakery.bakery"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
