# Generated by Django 5.1.1 on 2024-10-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0012_alter_bakeryaddress_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakeryaddress",
            name="delivery",
            field=models.CharField(
                blank=True,
                choices=[("DL", "Delivery"), ("SP", "Shipping")],
                max_length=2,
                null=True,
                verbose_name="Delivery",
            ),
        ),
    ]
