# Generated by Django 5.1.1 on 2024-10-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0014_alter_bakeryaddress_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bakeryaddress",
            name="delivery",
            field=models.CharField(
                choices=[("BL", "Billing"), ("SP", "Shipping")],
                default="BL",
                max_length=2,
                verbose_name="Delivery",
            ),
        ),
    ]
