# Generated by Django 5.1.1 on 2024-12-04 10:28

import product.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0016_alter_bakeryaddress_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bakery",
            name="name",
            field=product.fields.CaseInsensitiveCharField(max_length=255, unique=True),
        ),
    ]
