# Generated by Django 5.1.1 on 2024-12-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0017_alter_bakery_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakeryaddress",
            name="contact_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bakeryaddress",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bakeryaddress",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
