# Generated by Django 5.1.1 on 2024-12-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0018_bakeryaddress_contact_no_bakeryaddress_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakery",
            name="email_reminders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bakery",
            name="newletter_reminders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bakery",
            name="sms_reminders",
            field=models.BooleanField(default=True),
        ),
    ]
