# Generated by Django 5.1.1 on 2025-01-09 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0019_bakery_email_reminders_bakery_newletter_reminders_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bakeryaddress",
            name="bakery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="bakery.bakery",
            ),
        ),
    ]
