# Generated by Django 5.1.1 on 2025-01-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0020_alter_bakeryaddress_bakery"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakery",
            name="customer_type",
            field=models.CharField(
                blank=True,
                choices=[("C", "Company"), ("I", "Individual")],
                default="C",
                max_length=2,
                null=True,
                verbose_name="Country",
            ),
        ),
    ]
