# Generated by Django 5.1.1 on 2025-01-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0021_bakery_customer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bakeryaddress",
            name="state",
            field=models.CharField(
                choices=[
                    ("Stockholm län", "Stockholm län"),
                    ("Västernorrland län", "Västernorrland län"),
                    ("Västmanland län", "Västmanland län"),
                    ("Västra Götaland län", "Västra Götaland län"),
                    ("Östergötland län", "Östergötland län"),
                    ("Dalarna län", "Dalarna län"),
                    ("Gävleborg län", "Gävleborg län"),
                    ("Gotland län", "Gotland län"),
                    ("Halland län", "Halland län"),
                    ("Jämtland län", "Jämtland län"),
                    ("Jönköping län", "Jönköping län"),
                    ("Kalmar län", "Kalmar län"),
                    ("Kristianstad län", "Kristianstad län"),
                    ("Kopparberg län", "Kopparberg län"),
                    ("Skåne län", "Skåne län"),
                    ("Södermanland län", "Södermanland län"),
                    ("Uppsala län", "Uppsala län"),
                    ("Värmland län", "Värmland län"),
                    ("Västerbotten län", "Västerbotten län"),
                    ("Blekinge län", "Blekinge län"),
                    ("Nordmaling län", "Nordmaling län"),
                    ("Örebro län", "Örebro län"),
                ],
                max_length=80,
                verbose_name="State",
            ),
        ),
    ]
