# Generated by Django 5.1.1 on 2025-02-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0023_alter_bakeryaddress_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakery",
            name="customer_id",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
