# Generated by Django 5.1.1 on 2025-03-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0024_bakery_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bakery",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="bakeryaddress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
