# Generated by Django 5.1.1 on 2025-03-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0025_alter_bakery_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakery",
            name="organization_no",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="bakery",
            name="vat_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
