# Generated by Django 5.1.1 on 2024-10-09 11:16

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_category_description_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                blank=True, choices=product.models.ProductStatus.choices, max_length=200
            ),
        ),
    ]
