# Generated by Django 5.1.1 on 2024-10-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "available"),
                    ("OUT_OF_STOCK", "out_of_stock"),
                    ("DISCONTINUED", "discontinued"),
                ],
                default="available",
                max_length=200,
            ),
        ),
    ]
