# Generated by Django 5.1.1 on 2024-10-10 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("focused_keyword", models.CharField(max_length=255)),
                ("seo_title", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
                (
                    "preview_as",
                    models.CharField(
                        choices=[("desktop", "desktop"), ("mobile", "mobile")],
                        default="mobile",
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productseo",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
