# Generated by Django 5.1.1 on 2024-10-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_productseo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[("Kilogram", "kg"), ("Gram", "g"), ("Litre", "litre")],
                        default="kg",
                        max_length=20,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reorder", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
