# Generated by Django 5.1.1 on 2024-10-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_productmaterial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmaterial",
            old_name="name",
            new_name="title",
        ),
    ]
