# Generated by Django 5.1.1 on 2024-10-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_rename_name_productmaterial_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaterial",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productmaterial",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="productmaterial",
            name="unit_of_measure",
            field=models.CharField(
                choices=[("kg", "Kilogram"), ("g", "Gram"), ("litre", "Litre")],
                default="kg",
                max_length=20,
            ),
        ),
    ]
