# Generated by Django 5.1.1 on 2024-10-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_productmaterial_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="barcode",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
