# Generated by Django 5.1.1 on 2024-10-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_productvariant_barcode_productvariant_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmaterial",
            old_name="title",
            new_name="name",
        ),
    ]
