# Generated by Django 5.1.1 on 2024-10-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_rename_title_productmaterial_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaterial",
            name="barcode",
            field=models.ImageField(blank=True, null=True, upload_to="barcode/"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="barcode",
            field=models.ImageField(blank=True, null=True, upload_to="barcode/"),
        ),
    ]
