# Generated by Django 5.1.1 on 2024-10-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_productmaterial_barcode_alter_productvariant_barcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmaterial",
            name="barcode",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="barcode",
        ),
    ]
