# Generated by Django 5.1.1 on 2024-10-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_remove_productmaterial_barcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="end_series",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="start_series",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
