# Generated by Django 5.1.1 on 2024-10-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_product_end_series_product_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="end_series",
        ),
        migrations.RemoveField(
            model_name="product",
            name="start_series",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="end_series",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="start_series",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
