# Generated by Django 5.1.1 on 2024-10-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_remove_product_end_series_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_tag",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "available"),
                    ("out_of_stock", "out_of_stock"),
                    ("discontinued", "discontinued"),
                ],
                default="available",
                max_length=200,
            ),
        ),
    ]
