# Generated by Django 5.1.1 on 2024-10-25 09:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_product_product_tag_alter_product_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariant",
            old_name="price",
            new_name="regular_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="end_series",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="start_series",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="productseo",
            name="meta_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="allow_backorders",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="manage_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sale_price_dates_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sale_price_dates_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="unit",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="weight",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("regular_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("sale_price_date_from", models.DateField(blank=True, null=True)),
                ("sale_price_date_to", models.DateField(blank=True, null=True)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=50)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("bulking_price_rules", models.JSONField(default=list)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
