# Generated by Django 5.1.1 on 2024-10-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_rename_price_productvariant_regular_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
    ]
