# Generated by Django 5.1.1 on 2024-10-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_remove_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="min_order_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="purchase_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_featured",
            field=models.BooleanField(default=True),
        ),
    ]
