# Generated by Django 5.1.1 on 2024-10-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0019_product_min_order_quantity_product_purchase_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productseo",
            name="focused_keyword",
            field=models.JSONField(default=list),
        ),
    ]
