# Generated by Django 5.1.1 on 2024-10-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0020_alter_productseo_focused_keyword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
    ]
