# Generated by Django 5.1.1 on 2024-10-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0021_remove_product_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="manage_stock",
        ),
        migrations.AlterField(
            model_name="inventory",
            name="sku",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="allow_backorders",
            field=models.CharField(
                choices=[("Do Not Allow", "Do Not Allow"), ("Allow", "Allow")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
