# Generated by Django 5.1.1 on 2024-10-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0022_remove_productvariant_manage_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="managed_stock",
            field=models.BooleanField(default=True),
        ),
    ]
