# Generated by Django 5.1.1 on 2024-10-27 14:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0025_alter_product_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_tag",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
