# Generated by Django 5.1.1 on 2024-10-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0026_alter_product_product_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
    ]
