# Generated by Django 5.1.1 on 2024-10-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0027_remove_product_sku"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="sale_price_date_from",
            new_name="sale_price_dates_from",
        ),
        migrations.RenameField(
            model_name="inventory",
            old_name="sale_price_date_to",
            new_name="sale_price_dates_to",
        ),
    ]
