# Generated by Django 5.1.1 on 2024-10-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0028_rename_sale_price_date_from_inventory_sale_price_dates_from_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "kg"),
                    ("grams", "grams"),
                    ("litre", "litre"),
                    ("unit", "unit"),
                    ("meter", "meter"),
                    ("inch", "inch"),
                    ("pieces", "pieces"),
                ],
                default="unit",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "kg"),
                    ("grams", "grams"),
                    ("litre", "litre"),
                    ("unit", "unit"),
                    ("meter", "meter"),
                    ("inch", "inch"),
                    ("pieces", "pieces"),
                ],
                default="unit",
                max_length=20,
            ),
        ),
    ]
