# Generated by Django 5.1.1 on 2024-10-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0030_inventory_created_at_inventory_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="end_series",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="start_series",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
