# Generated by Django 5.1.1 on 2024-11-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0031_productvariant_end_series_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaterial",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
