# Generated by Django 5.1.1 on 2024-11-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0031_productvariant_end_series_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_image",
            field=models.ImageField(blank=True, null=True, upload_to="category/images"),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="category_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="subcategory/images"
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
