# Generated by Django 5.1.1 on 2024-11-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0032_productmaterial_is_active"),
        ("product", "0033_alter_subcategory_category"),
    ]

    operations = []
