# Generated by Django 5.1.1 on 2024-11-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0034_merge_20241106_0613"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("title", models.CharField(max_length=255, unique=True)),
                (
                    "product_variant",
                    models.ManyToManyField(
                        related_name="product_collection", to="product.productvariant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
