# Generated by Django 5.1.1 on 2024-11-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0036_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="end_series",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="start_series",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ProductCollection",
        ),
    ]
