# Generated by Django 5.1.1 on 2024-11-08 11:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0037_inventory_end_series_inventory_start_series_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
