# Generated by Django 5.1.1 on 2024-11-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0038_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_category_products",
                to="product.subcategory",
            ),
        ),
    ]
