# Generated by Django 5.1.1 on 2024-11-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0039_product_sub_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subcategory",
            old_name="category",
            new_name="parent",
        ),
    ]
