# Generated by Django 5.1.1 on 2024-11-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0040_rename_category_subcategory_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
