# Generated by Django 5.1.1 on 2024-11-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0041_subcategory_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="total_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
