# Generated by Django 5.1.1 on 2024-11-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0042_inventory_total_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sub_category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="product.category"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ManyToManyField(
                blank=True,
                related_name="sub_category_products",
                to="product.subcategory",
            ),
        ),
    ]
