# Generated by Django 5.1.1 on 2024-11-19 06:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0043_remove_product_category_remove_product_sub_category_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="end_series",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="regular_price",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="sale_price",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="sale_price_dates_from",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="sale_price_dates_to",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="start_series",
        ),
        migrations.AddField(
            model_name="inventory",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="product.productvariant",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inventory",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="product.product",
            ),
        ),
    ]
