# Generated by Django 5.1.1 on 2024-11-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0044_remove_inventory_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
