# Generated by Django 5.1.1 on 2024-11-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0045_inventory_created_at_inventory_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="weight",
        ),
    ]
