# Generated by Django 5.1.1 on 2024-11-19 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0046_remove_productvariant_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="product.productvariant",
            ),
        ),
    ]
