# Generated by Django 5.1.1 on 2024-11-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0047_alter_inventory_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="product",
        ),
    ]
