# Generated by Django 5.1.1 on 2024-11-21 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0048_remove_inventory_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="product_variant",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="product.productvariant",
            ),
        ),
    ]
