# Generated by Django 5.1.1 on 2024-11-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0049_alter_inventory_product_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
