# Generated by Django 5.1.1 on 2024-12-04 06:43

import product.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0050_product_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=product.fields.CaseInsensitiveCharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="sku",
            field=product.fields.CaseInsensitiveCharField(
                blank=True, max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=product.fields.CaseInsensitiveCharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="productmaterial",
            name="name",
            field=product.fields.CaseInsensitiveCharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=product.fields.CaseInsensitiveCharField(max_length=225, unique=True),
        ),
    ]
