# Generated by Django 5.1.1 on 2024-12-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0051_alter_category_name_alter_inventory_sku_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productvariant",
            options={"ordering": ["created_at"]},
        ),
    ]
