# Generated by Django 5.1.1 on 2024-12-12 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0053_favouriteitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FavouriteItem",
        ),
    ]
