# Generated by Django 5.1.1 on 2024-12-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0056_category_is_deleted_productmaterial_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
