# Generated by Django 5.1.1 on 2024-12-24 07:13

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0057_subcategory_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="bulking_price_rules",
            field=models.JSONField(default=product.models.default_bulking_price_rules),
        ),
    ]
