# Generated by Django 5.1.1 on 2024-12-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0058_alter_inventory_bulking_price_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hot_deal",
            field=models.BooleanField(default=False),
        ),
    ]
