# Generated by Django 5.1.1 on 2024-12-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0059_product_hot_deal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "kg"),
                    ("grams", "grams"),
                    ("litre", "litre"),
                    ("unit", "unit"),
                    ("meter", "meter"),
                    ("pieces", "pieces"),
                    ("mg", "mg"),
                    ("lb", "lb"),
                    ("oz", "oz"),
                    ("ml", "ml"),
                    ("cup", "cup"),
                    ("tablespoon", "tablespoon"),
                    ("teaspoon", "teaspoon"),
                    ("slice", "slice"),
                ],
                default="unit",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productmaterial",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogram"),
                    ("g", "Gram"),
                    ("litre", "Litre"),
                    ("mg", "Milligram"),
                    ("lb", "Pound"),
                    ("oz", "Ounce"),
                    ("ml", "Millilitre"),
                    ("cup", "Cup"),
                    ("tbsp", "Tablespoon"),
                    ("tsp", "Teaspoon"),
                    ("piece", "Piece"),
                    ("slice", "Slice"),
                ],
                default="kg",
                max_length=20,
            ),
        ),
    ]
