# Generated by Django 5.1.1 on 2025-01-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0060_alter_inventory_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="barcode",
            field=models.ImageField(
                blank=True, null=True, unique=True, upload_to="barcodes/"
            ),
        ),
    ]
