# Generated by Django 5.1.1 on 2025-01-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0061_alter_inventory_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="barcode",
            field=models.ImageField(blank=True, null=True, upload_to="barcodes/"),
        ),
    ]
