# Generated by Django 5.1.1 on 2025-01-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0062_alter_inventory_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="unique_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
