# Generated by Django 5.1.1 on 2025-01-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0063_inventory_unique_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="total_quantity",
            field=models.IntegerField(default=1),
        ),
    ]
