# Generated by Django 5.1.1 on 2025-01-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0064_alter_inventory_total_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productseo",
            name="seo_title",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
