# Generated by Django 5.1.1 on 2025-01-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0065_alter_productseo_seo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="unique_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
