# Generated by Django 5.1.1 on 2025-01-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0066_alter_inventory_unique_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="sale_active",
            field=models.BooleanField(default=False),
        ),
    ]
