# Generated by Django 5.1.1 on 2025-02-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0068_productmaterial_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaterial",
            name="barcode",
            field=models.ImageField(
                blank=True, null=True, upload_to="material_barcodes/"
            ),
        ),
    ]
