# Generated by Django 5.1.1 on 2025-02-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0069_productmaterial_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaterial",
            name="unique_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
