# Generated by Django 5.1.1 on 2025-02-12 13:53

import product.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0070_productmaterial_unique_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="sku",
            field=product.fields.CaseInsensitiveCharField(
                blank=True, max_length=100, null=True, unique=True
            ),
        ),
    ]
