# Generated by Django 5.1.1 on 2025-02-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0071_alter_inventory_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="allow_backorders",
            field=models.CharField(
                choices=[("Do Not Allow", "Do Not Allow"), ("Allow", "Allow")],
                default="Do Not Allow",
                max_length=50,
            ),
        ),
    ]
