# Generated by Django 5.1.1 on 2025-02-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0072_alter_productvariant_allow_backorders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="sale_active",
            field=models.BooleanField(default=True),
        ),
    ]
