# Generated by Django 5.1.1 on 2025-02-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0073_alter_inventory_sale_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="sale_active",
            field=models.BooleanField(default=False),
        ),
    ]
