# Generated by Django 5.1.1 on 2025-02-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0074_alter_inventory_sale_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productseo",
            name="meta_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
