# Generated by Django 5.1.1 on 2025-02-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0075_alter_productseo_meta_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
