# Generated by Django 5.1.1 on 2024-10-24 09:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0016_product_product_tag_alter_product_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_title", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField()),
                ("status", models.BooleanField(default=True)),
                ("cook_time", models.PositiveIntegerField()),
                ("preparation_time", models.PositiveIntegerField()),
                ("serving_size", models.PositiveIntegerField()),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[("E", "Easy"), ("M", "Medium"), ("H", "Hard")],
                        max_length=1,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="product.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_count", models.PositiveIntegerField()),
                ("instructions", models.TextField()),
                (
                    "dietary_plan",
                    models.CharField(
                        choices=[("GF", "Gluten-Free"), ("DF", "Dairy-Free")],
                        max_length=2,
                    ),
                ),
                (
                    "allergen_information",
                    models.CharField(choices=[("CN", "Contains Nuts")], max_length=2),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructions",
                        to="recipe.recipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_of_measure", models.CharField(max_length=50, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipe.recipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="recipes/")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_images",
                        to="recipe.recipe",
                    ),
                ),
            ],
        ),
    ]
