# Generated by Django 5.1.1 on 2024-10-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_ingredient_created_at_ingredient_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="serving_size",
            field=models.PositiveIntegerField(max_length=99999),
        ),
    ]
