# Generated by Django 5.1.1 on 2024-10-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_alter_recipe_serving_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="unit_of_measure",
            field=models.CharField(max_length=50),
        ),
    ]
