# Generated by Django 5.1.1 on 2024-10-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_alter_ingredient_unit_of_measure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="serving_size",
            field=models.PositiveIntegerField(),
        ),
    ]
