# Generated by Django 5.1.1 on 2024-11-07 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0005_alter_recipe_serving_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instruction",
            name="allergen_information",
        ),
        migrations.RemoveField(
            model_name="instruction",
            name="dietary_plan",
        ),
        migrations.AddField(
            model_name="recipe",
            name="allergen_information",
            field=models.CharField(
                choices=[("CN", "Contains Nuts")],
                default=django.utils.timezone.now,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="dietary_plan",
            field=models.CharField(
                choices=[("GF", "Gluten-Free"), ("DF", "Dairy-Free")],
                default=django.utils.timezone.now,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
