# Generated by Django 5.1.1 on 2024-11-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0006_remove_instruction_allergen_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
    ]
