# Generated by Django 5.1.1 on 2024-11-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0043_remove_product_category_remove_product_sub_category_and_more",
        ),
        ("recipe", "0007_alter_recipeimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="category",
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="recipes_category", to="product.category"
            ),
        ),
    ]
