# Generated by Django 5.1.1 on 2024-11-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0044_remove_inventory_created_at_and_more"),
        ("recipe", "0008_remove_recipe_category_recipe_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.ManyToManyField(related_name="recipes", to="product.category"),
        ),
    ]
