# Generated by Django 5.1.1 on 2024-11-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0009_alter_recipe_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
