# Generated by Django 5.1.1 on 2024-12-04 06:43

import product.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0010_alter_recipe_recipe_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogram"),
                    ("g", "Gram"),
                    ("litre", "Litre"),
                    ("mg", "Milligram"),
                    ("lb", "Pound"),
                    ("oz", "Ounce"),
                    ("litre", "Litre"),
                    ("ml", "Millilitre"),
                    ("cup", "Cup"),
                    ("tbsp", "Tablespoon"),
                    ("tsp", "Teaspoon"),
                    ("piece", "Piece"),
                    ("slice", "Slice"),
                ],
                default="kg",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_title",
            field=product.fields.CaseInsensitiveCharField(max_length=200, unique=True),
        ),
    ]
