# Generated by Django 5.1.1 on 2024-12-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0011_alter_ingredient_unit_of_measure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
