# Generated by Django 5.1.1 on 2025-01-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0012_recipe_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("publish", "Publish"),
                    ("draft", "Draft"),
                    ("delete", "Delete"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
