# Generated by Django 5.1.1 on 2025-01-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0014_alter_recipe_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="dietary_plan",
            field=models.CharField(
                choices=[
                    ("GF", "Gluten-Free"),
                    ("DF", "Dairy-Free"),
                    ("VEG", "Vegetarian"),
                    ("VEGAN", "Vegan"),
                    ("NF", "Nut-Free"),
                    ("PA", "Paleo"),
                    ("KETO", "Ketogenic"),
                    ("LC", "Low-Carb"),
                    ("PESC", "Pescatarian"),
                    ("HAL", "Halal"),
                    ("KOS", "Kosher"),
                    ("SF", "Soy-Free"),
                    ("SFREE", "Sugar-Free"),
                    ("ORG", "Organic"),
                    ("W30", "Whole30"),
                    ("LFOD", "Low-FODMAP"),
                    ("HP", "High-Protein"),
                    ("RAW", "Raw Food"),
                    ("FLEX", "Flexitarian"),
                    ("LS", "Low-Sodium"),
                ],
                max_length=100,
            ),
        ),
    ]
