# Generated by Django 5.1.1 on 2025-02-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0016_recipe_updated_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="allergen_information",
        ),
        migrations.AddField(
            model_name="recipe",
            name="allergen_information",
            field=models.ManyToManyField(blank=True, to="recipe.allergen"),
        ),
    ]
