# Generated by Django 5.1.1 on 2025-02-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0017_allergen_remove_recipe_allergen_information_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeNutrition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("calories", models.FloatField(default=0.0)),
                ("protein", models.FloatField(default=0.0)),
                ("fat", models.FloatField(default=0.0)),
                ("carbohydrates", models.FloatField(default=0.0)),
                ("energy", models.FloatField(default=0.0)),
                ("fiber", models.FloatField(default=0.0)),
                ("salt", models.FloatField(default=0.0)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutritions",
                        to="recipe.recipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
