# Generated by Django 5.1.1 on 2025-02-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0018_recipenutrition"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipenutrition",
            name="nutrition_image",
            field=models.ImageField(blank=True, null=True, upload_to="nutrition/"),
        ),
    ]
