# Generated by Django 5.1.1 on 2025-02-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0019_recipenutrition_nutrition_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipenutrition",
            name="sugar",
            field=models.FloatField(default=0.0),
        ),
    ]
