# Generated by Django 5.1.1 on 2025-02-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0021_alter_recipe_allergen_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="allergen_information",
            field=models.ManyToManyField(blank=True, to="recipe.allergen"),
        ),
    ]
