# Generated by Django 5.1.1 on 2025-03-05 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0023_alter_ingredient_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="dietary_plan",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
